PLOT_RANGE_DROPDOWN = "plot-range-dropdown"
DATA_TYPE_DROPDOWN = "data-type-dropdown"

TOTAL_PAYMENTS = "total-payments"
TOTAL_INTEREST_PAYMENTS = "total-interest-payments"

CURRENT_MONTH_PAYMENT = "current-month-payment"

MORTGAGE_AGREEMENT_MODAL = "mortgage-agreement-modal"
MORTGAGE_AGREEMENT_MODAL_OPEN = "mortgage-agreement-modal-open"
MORTGAGE_AGREEMENT_MODAL_BODY = "mortgage-agreement-modal-body"
MORTGAGE_AGREEMENT_MODAL_PREVIOUS = "mortgage-agreement-modal-previous"
MORTGAGE_AGREEMENT_MODAL_NEXT = "mortgage-agreement-modal-next"
MORTGAGE_AGREEMENT_MODAL_EDIT = "mortgage-agreement-modal-edit"
MORTGAGE_AGREEMENT_MODAL_DELETE = "mortgage-agreement-modal-delete"

MORTGAGE_EDIT_MODAL = "mortgage-edit-modal"
MORTGAGE_EDIT_MODAL_CLOSE = "mortgage-edit-modal-close"
MORTGAGE_EDIT_MODAL_NAME = "mortgage-edit-modal-name"
MORTGAGE_EDIT_MODAL_RATE = "mortgage-edit-modal-rate"
MORTGAGE_EDIT_MODAL_START = "mortgage-edit-modal-start"
MORTGAGE_EDIT_MODAL_TERM_YEARS = "mortgage-edit-modal-term-years"
MORTGAGE_EDIT_MODAL_TERM_MOTHS = "mortgage-edit-modal-term-months"
MORTGAGE_EDIT_MODAL_FIXED_TERM_YEARS = "mortgage-edit-modal-fixed-term-years"
MORTGAGE_EDIT_MODAL_FIXED_TERM_MOTHS = "mortgage-edit-modal-fixed-term-months"
MORTGAGE_EDIT_MODAL_PRINCIPLE = "mortgage-edit-modal-principle"

MORTGAGE_ADD_MODAL = "mortgage-add-modal"
MORTGAGE_ADD_MODAL_OPEN = "mortgage-add-modal-open"
MORTGAGE_ADD_MODAL_CLOSE = "mortgage-add-modal-close"
MORTGAGE_ADD_MODAL_NAME = "mortgage-add-modal-name"
MORTGAGE_ADD_MODAL_RATE = "mortgage-add-modal-rate"
MORTGAGE_ADD_MODAL_START = "mortgage-add-modal-start"
MORTGAGE_ADD_MODAL_TERM_YEARS = "mortgage-add-modal-term-years"
MORTGAGE_ADD_MODAL_TERM_MOTHS = "mortgage-add-modal-term-months"
MORTGAGE_ADD_MODAL_FIXED_TERM_YEARS = "mortgage-add-modal-fixed-term-years"
MORTGAGE_ADD_MODAL_FIXED_TERM_MOTHS = "mortgage-add-modal-fixed-term-months"
MORTGAGE_ADD_MODAL_PRINCIPLE = "mortgage-add-modal-principle"

ADD_OVERPAYMENT_MODAL = "add-overpayment-modal"
ADD_OVERPAYMENT_MODAL_OPEN = "add-overpayment-modal-open"
ADD_OVERPAYMENT_MODAL_CLOSE = "add-overpayment-modal-close"
ADD_OVERPAYMENT_MODAL_DATE = "add-overpayment-modal-date"
ADD_OVERPAYMENT_MODAL_AMOUNT = "add-overpayment-modal-amount"

OVERPAYMENT_MODAL = "overpayment-modal"
OVERPAYMENT_MODAL_OPEN = "overpayment-modal-open"
OVERPAYMENT_MODAL_ADD = "overpayment-modal-add"
OVERPAYMENT_MODAL_CLOSE = "overpayment-modal-close"

LINE_CHART = "line-chart"

TOTAL_PAYMENTS = "total-payments"
TOTAL_INTEREST_PAYMENTS = "total-interest-payments"

CURRENT_MONTH_PAYMENT = "current-month-payment"
